services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # Exporters
    #
    Apisearch\Exporter\ExporterCollection:
    Apisearch\Exporter\IndexExporter:
    Apisearch\Exporter\JSONExporter:
        tags: ['apisearch.exporter']
    Apisearch\Exporter\YamlExporter:
        tags: ['apisearch.exporter']
    Apisearch\Exporter\CSVExporter:
        tags: ['apisearch.exporter']
