services:

    apisearch.repository_bucket:
        class: Apisearch\Repository\RepositoryBucket

    apisearch.app_repository_bucket:
        class: Apisearch\App\AppRepositoryBucket
        arguments:
            - "%apisearch.repository_configuration%"

    apisearch.user_repository_bucket:
        class: Apisearch\User\UserRepositoryBucket

    apisearch.event_repository_bucket:
        class: Apisearch\Event\EventRepositoryBucket

    apisearch.log_repository_bucket:
        class: Apisearch\Log\LogRepositoryBucket

    #
    # Mocks
    #
    apisearch.repository_mock:
        class: Apisearch\Repository\MockRepository

    apisearch.app_repository_mock:
        class: Apisearch\App\MockAppRepository

    apisearch.events_repository_mock:
        class: Apisearch\Event\MockEventRepository

    apisearch.logs_repository_mock:
        class: Apisearch\Log\MockLogRepository

    apisearch.user_repository_mock:
        class: Apisearch\User\MockUserRepository