services:

    Apisearch\Repository\RepositoryBucket:
    Apisearch\User\UserRepositoryBucket:
    Apisearch\App\AppRepositoryBucket:
        arguments:
            - "%apisearch.repository_configuration%"


    #
    # Mocks
    #
    Apisearch\Repository\MockRepository:
    Apisearch\App\MockAppRepository:
    Apisearch\User\MockUserRepository: