version: 2
jobs:
  test-php73:
    docker:
      - image: circleci/php:7.3-cli

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests / Symfony 4^3
          command: |
            composer update -n --prefer-dist --prefer-lowest --no-suggest
            php vendor/bin/phpunit

      - run:
          name: Run tests / Symfony 5^0
          command: |
            composer update -n --prefer-dist --no-suggest
            php vendor/bin/phpunit

  test-php74:
    docker:
      - image: circleci/php:7.4-cli

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests / Symfony 5^0
          command: |
            composer update -n --prefer-dist --no-suggest
            php vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - test-php73
      - test-php74