version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli
      - image: redis:4-alpine

      - image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.4"
        environment:
          cluster.name: apisearch
          http.host: 0.0.0.0
          transport.host: 0.0.0.0
          ES_JAVA_OPTS: "-Xms1g -Xmx1g"
          node.max_local_storage_nodes: 10
          discovery.type: single-node

      - image: "apisearchio/search-server:latest"
        environment:
          APISEARCH_GOD_TOKEN: 0e4d75ba-c640-44c1-a745-06ee51db4e93
          APISEARCH_READONLY_TOKEN: 410806ed-f2c2-8d22-96ea-7fb68026df34
          APISEARCH_PING_TOKEN: 6326d504-0a5f-f1ae-7344-8e70b75fcde9
          APISEARCH_ENABLED_PLUGINS: redis_storage
          ELASTICSEARCH_HOST: localhost
          ELASTICSEARCH_PORT: 9200
          ELASTICSEARCH_REFRESH_ON_WRITE: 1
          REDIS_STORAGE_HOST: localhost
          REDIS_STORAGE_PORT: 6379

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            composer install -n --prefer-dist --no-suggest
            sh .circleci/run-tests
